### ISSUE TITLE
Simplify SDK initialization

### ISSUE THREAD

**Issue by aksalj** [ElarianLtd/dotnet-sdk#2]
It would be great to remove the need to supply the server address. i.e. `new ElarianClient(new ElarianAppCredentials())`

**Comment by Giorgi** [comment]
What if you have separate dev and prod environments?

**Comment by aksalj** [comment]
No need, because there is only one environment as far as the end-user is concerned

**Comment by Giorgi** [comment]
In that case, how do users indicate whether to use wss or tcp address?

**Comment by aksalj** [comment]
They don't need to. C# should just use tcp. wss is only used for js in the browser.
