### ISSUE TITLE
Missing notification handlers

### ISSUE THREAD

**Issue by aksalj** [ElarianLtd/dotnet-sdk#4]
Handlers for the following events are missing

```
receivedSms
receivedFbMessenger
receivedTelegram
receivedWhatsapp
receivedEmail
```

**Comment by Giorgi** [comment]
[ReceivedMessageNotification](https://github.com/ElarianLtd/dotnet-sdk/blob/master/Elarian.Net/ElarianClient.cs#L206) is used for sms notifications. For others it uses [ReceivedMediaNotification](https://github.com/ElarianLtd/dotnet-sdk/blob/master/Elarian.Net/ElarianClient.cs#L209) and the notification object has a channel property

**Comment by aksalj** [comment]
Yes, it needs to be broken up into events for each of the channel types - to match the SDK spec

**Comment by aksalj** [comment]
Fixed with https://github.com/ElarianLtd/dotnet-sdk/pull/8
