### ISSUE TITLE
Notification response

### ISSUE THREAD

**Issue by aksalj** [ElarianLtd/dotnet-sdk#5]
Notification handlers need to be able to respond with some data when called. i.e. when a USSD or Voice call comes in, a response is expected. The default behaviour [here](https://github.com/ElarianLtd/dotnet-sdk/blob/503e8945a0c950b887e6ac9e34e12bc4c4a51a34/Elarian.Net/ElarianClientBase.cs#L56) seems to respond with an empty payload

**Comment by Giorgi** [comment]
Is it described in spec?

**Comment by aksalj** [comment]
Yes, in the [section](https://github.com/ElarianLtd/sdk-spec) that describes notification handlers.
